run:
  timeout: 6m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - exportloopref
    - gocritic
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/buildpacks/libcnb

issues:
  exclude-rules:
  - path: _test\.go
    linters: errcheck
